on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Run at midnight every Sunday

jobs:
  rotate_api_tokens:
    if: ${{ secrets.ARCGIS_TOKEN != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: generate_api_token

      - name: Run generate_api_token script
        run: node generate_api_token/index.js
        env:
          ARCGIS_TOKEN: ${{ secrets.ARCGIS_TOKEN }}

      - name: Set API token in AWS
        run: 'echo TODO: set API token from token.json/token'

      - name: Clean up temp files
        if: always()
        run: rm -f token.json